openapi: 3.0.0
info:
  title: User Management API
  version: 1.0.0
paths:
  /token:
    post:
      summary: Refresh tokens
      responses:
        "200":
          description: Refresh tokens successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
components:
  schemas:
    SuccessResponse:
      x-go-optional-value: true
      type: object
      properties:
        result:
          type: string